version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: metadata
      MYSQL_USER: sql_user
      MYSQL_PASSWORD: sql_user_password
    volumes:
     ./mnt/docker/mariadb:/var/lib/mysql